name: Python CI


on: 
  push:                  # Kind of a Mandatory field, that defines the event, and when it triggers, what process will happen 
    branches: 
        - main
  pull_request:
    branches:
        - main

jobs:
    build: 
        runs-on: self-hosted
        steps:
            - name: Checking the code 
              uses: actions/checkout@v2
            - name: Check Python Installation
              run: |
                if (Get-Command python -ErrorAction SilentlyContinue) {
                  echo "Python is already installed."
                } else {
                  echo "Python is not installed. Please install Python 3.10.x."
                  exit 1  # Fail the job if Python is not installed
                }
            - name: checking the dir 
              run: dir 
            - name: Installing Packages
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                
            - name: Run tests
              run: pytest mathopertest.py
